name: Deploy MM Bot

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Очистить директорию
        run: rm -rf ./mm_bot || true

      - name: Клонировать репозиторий
        uses: actions/checkout@v4

      - name: Остановить контейнер
        run: docker compose down || true

      - name: Построить и запустить заново
        run: docker compose up -d --build

      - name: Проверить логи на старт бота
        run: |
          sleep 60
          if ! docker logs mm_bot 2>&1 | grep -q "Бот запущен."; then
            echo "❌ Бот не запустился"
            docker logs mm_bot
            exit 1
          fi
