name: Deploy MM Bot

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Очистить директорию
        run: rm -rf ./mm_bot || true

      - name: Клонировать репозиторий
        uses: actions/checkout@v4

      - name: Остановить контейнер
        run: docker compose down || true

      - name: Построить и запустить заново
        run: docker compose up -d --build

      - name: Чтение лога
        run: docker logs --tail=50 mm_bot
